version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ApiSarbideExt
hooks:
  BeforeInstall:
    - location: tests/before.sh    
      timeout: 300
      runas: root
  AfterInstall:
    - location: tests/after.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: tests/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: tests/stop_server.sh
      timeout: 300
      runas: root
