version: 0.0
os: linux
files:
  - source: /
    destination: /srv/www/ApiSarbideExt
  - source: config/nginx.conf
    destination: /etc/nginx/nginx.conf
hooks:
  BeforeInstall:
    - location: tests/mueve.sh    
      timeout: 300
      runas: root
  ApplicationStart:
    - location: tests/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: tests/stop_server.sh
      timeout: 300
      runas: root
